version: '3'
services:
  frontend:
    build: .
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: yarn start
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

  # backend:
  #   build: .
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/app
  #   command: yarn run json-server -w db.json --host 0.0.0.0 --p 80
  #   ports:
  #     - 80:80
