name: Actions Workflow

# on: [push, pull_request]
on:
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git pull origin master
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add .
          git commit -m "random"
          git push origin master
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          eccho $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        if: failure()
        uses: actions/checkout@v1
      - name: List Files After Checkout
        if: always()
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: john
      - name: Log Greet time
        run: echo "${{ steps.greet.outputs.time }}"
