name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install
        run: yarn install
      - name: eslint
        run: yarn eslint
      - name: jest test
        run: yarn test
        env:
          CI: true

